/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 24d00bb3851f1481ac73ea01e4d0cd89)
interface __BaseEnv_Env {
	chatbot_branding: KVNamespace;
	R2: R2Bucket;
	AI: Ai;
	R2_PUBLIC_URL: "https://chatbot-images.acmecorp.work";
	GUARDRAILS_GATEWAY: "realacmecorp-zt-demos";
	NO_GUARDRAILS_GATEWAY: "realacmecorp-zt-demos-no-guardrail";
	ACCESS_TEAM_DOMAIN: "realacmecorp.cloudflareaccess.com";
	ACCESS_AUD: "b14960624a389d5c55b745220c224a717fd0a3c1055af637965c310a87c13046";
	CLOUDFLARE_ACCOUNT_ID: string;
	CLOUDFLARE_API_TOKEN: string;
	ChatAgent: DurableObjectNamespace<import("./src/server").ChatAgent>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "ChatAgent";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "R2_PUBLIC_URL" | "GUARDRAILS_GATEWAY" | "NO_GUARDRAILS_GATEWAY" | "ACCESS_TEAM_DOMAIN" | "ACCESS_AUD" | "CLOUDFLARE_ACCOUNT_ID" | "CLOUDFLARE_API_TOKEN">> {}
}
