/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: b684d6848d3bcd0996c57ed4035326e3)
interface __BaseEnv_Env {
	chatbot_branding: KVNamespace;
	R2: R2Bucket;
	AI: Ai;
	R2_PUBLIC_URL: "https://chatbot-images.acmecorp.work";
	GUARDRAILS_GATEWAY: "realacmecorp-zt-demos";
	NO_GUARDRAILS_GATEWAY: "realacmecorp-zt-demos-no-guardrail";
	CLOUDFLARE_ACCOUNT_ID: string;
	CLOUDFLARE_API_TOKEN: string;
	ChatAgent: DurableObjectNamespace<import("./src/server").ChatAgent>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "ChatAgent";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "R2_PUBLIC_URL" | "GUARDRAILS_GATEWAY" | "NO_GUARDRAILS_GATEWAY" | "CLOUDFLARE_ACCOUNT_ID" | "CLOUDFLARE_API_TOKEN">> {}
}
